export type GenerateTokenResponse = {
    access_token: string
    config: {
      mode: string
      name: string
      about: string
      edition: string
      version: string
      copyright: string
      flags: string
      baseUri: string
      staticUri: string
      cssUri: string
      jsUri: string
      manifestUri: string
      apiUri: string
      contentUri: string
      videoUri: string
      wallpaperUri: string
      siteUrl: string
      siteDomain: string
      siteAuthor: string
      siteTitle: string
      siteCaption: string
      siteDescription: string
      sitePreview: string
      legalInfo: string
      legalUrl: string
      appName: string
      appMode: string
      appIcon: string
      appColor: string
      restart: boolean
      debug: boolean
      trace: boolean
      test: boolean
      demo: boolean
      sponsor: boolean
      readonly: boolean
      uploadNSFW: boolean
      public: boolean
      authMode: string
      usersPath: string
      loginUri: string
      registerUri: string
      passwordLength: number
      passwordResetUri: string
      experimental: boolean
      albumCategories: any
      albums: Array<any>
      cameras: Array<any>
      lenses: Array<{
        ID: number
        Slug: string
        Name: string
        Make: string
        Model: string
        Type: string
      }>
      countries: Array<{
        ID: string
        Slug: string
        Name: string
      }>
      people: Array<any>
      thumbs: Array<{
        size: string
        usage: string
        w: number
        h: number
      }>
      tier: number
      membership: string
      customer: string
      mapKey: string
      downloadToken: string
      previewToken: string
      disable: {
        restart: boolean
        webdav: boolean
        settings: boolean
        places: boolean
        backups: boolean
        tensorflow: boolean
        faces: boolean
        classification: boolean
        ffmpeg: boolean
        exiftool: boolean
        vips: boolean
        sips: boolean
        darktable: boolean
        rawtherapee: boolean
        imagemagick: boolean
        heifconvert: boolean
        vectors: boolean
        jpegxl: boolean
        raw: boolean
      }
      count: {
        all: number
        photos: number
        live: number
        videos: number
        cameras: number
        lenses: number
        countries: number
        hidden: number
        archived: number
        favorites: number
        review: number
        stories: number
        private: number
        albums: number
        private_albums: number
        moments: number
        private_moments: number
        months: number
        private_months: number
        states: number
        private_states: number
        folders: number
        private_folders: number
        files: number
        people: number
        places: number
        labels: number
        labelMaxPhotos: number
      }
      pos: {
        uid: string
        cid: string
        utc: string
        lat: number
        lng: number
      }
      years: any
      colors: Array<{
        Example: string
        Name: string
        Slug: string
      }>
      categories: Array<any>
      clip: number
      server: {
        cores: number
        routines: number
        memory: {
          total: number
          free: number
          used: number
          reserved: number
          info: string
        }
      }
      settings: {
        ui: {
          scrollbar: boolean
          zoom: boolean
          theme: string
          language: string
          timeZone: string
        }
        search: {
          batchSize: number
        }
        maps: {
          animate: number
          style: string
        }
        features: {
          account: boolean
          albums: boolean
          archive: boolean
          delete: boolean
          download: boolean
          edit: boolean
          estimates: boolean
          favorites: boolean
          files: boolean
          folders: boolean
          import: boolean
          labels: boolean
          library: boolean
          logs: boolean
          moments: boolean
          people: boolean
          places: boolean
          private: boolean
          ratings: boolean
          reactions: boolean
          review: boolean
          search: boolean
          services: boolean
          settings: boolean
          share: boolean
          upload: boolean
          videos: boolean
        }
        import: {
          path: string
          move: boolean
        }
        index: {
          path: string
          convert: boolean
          rescan: boolean
          skipArchived: boolean
        }
        stack: {
          uuid: boolean
          meta: boolean
          name: boolean
        }
        share: {
          title: string
        }
        download: {
          name: string
          disabled: boolean
          originals: boolean
          mediaRaw: boolean
          mediaSidecar: boolean
        }
        templates: {
          default: string
        }
      }
      acl: {
        albums: {
          access_all: boolean
          access_library: boolean
          access_own: boolean
          access_shared: boolean
          create: boolean
          delete: boolean
          download: boolean
          full_access: boolean
          manage: boolean
          rate: boolean
          react: boolean
          share: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
        calendar: {
          access_all: boolean
          access_library: boolean
          access_own: boolean
          access_shared: boolean
          create: boolean
          delete: boolean
          download: boolean
          full_access: boolean
          manage: boolean
          rate: boolean
          react: boolean
          share: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
        config: {
          access_all: boolean
          access_library: boolean
          access_own: boolean
          access_shared: boolean
          create: boolean
          delete: boolean
          download: boolean
          full_access: boolean
          manage: boolean
          rate: boolean
          react: boolean
          share: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
        default: {
          access_all: boolean
          access_library: boolean
          access_own: boolean
          access_shared: boolean
          create: boolean
          delete: boolean
          download: boolean
          full_access: boolean
          manage: boolean
          rate: boolean
          react: boolean
          share: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
        favorites: {
          access_all: boolean
          access_library: boolean
          access_own: boolean
          access_shared: boolean
          create: boolean
          delete: boolean
          download: boolean
          full_access: boolean
          manage: boolean
          rate: boolean
          react: boolean
          share: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
        feedback: {
          access_all: boolean
          access_library: boolean
          access_own: boolean
          access_shared: boolean
          create: boolean
          delete: boolean
          download: boolean
          full_access: boolean
          manage: boolean
          rate: boolean
          react: boolean
          share: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
        files: {
          access_all: boolean
          access_library: boolean
          access_own: boolean
          access_shared: boolean
          create: boolean
          delete: boolean
          download: boolean
          full_access: boolean
          manage: boolean
          rate: boolean
          react: boolean
          share: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
        folders: {
          access_all: boolean
          access_library: boolean
          access_own: boolean
          access_shared: boolean
          create: boolean
          delete: boolean
          download: boolean
          full_access: boolean
          manage: boolean
          rate: boolean
          react: boolean
          share: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
        labels: {
          access_all: boolean
          access_library: boolean
          access_own: boolean
          access_shared: boolean
          create: boolean
          delete: boolean
          download: boolean
          full_access: boolean
          manage: boolean
          rate: boolean
          react: boolean
          share: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
        logs: {
          access_all: boolean
          access_library: boolean
          access_own: boolean
          access_shared: boolean
          create: boolean
          delete: boolean
          download: boolean
          full_access: boolean
          manage: boolean
          rate: boolean
          react: boolean
          share: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
        metrics: {
          access_all: boolean
          access_library: boolean
          access_own: boolean
          access_shared: boolean
          create: boolean
          delete: boolean
          download: boolean
          full_access: boolean
          manage: boolean
          rate: boolean
          react: boolean
          share: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
        moments: {
          access_all: boolean
          access_library: boolean
          access_own: boolean
          access_shared: boolean
          create: boolean
          delete: boolean
          download: boolean
          full_access: boolean
          manage: boolean
          rate: boolean
          react: boolean
          share: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
        passcode: {
          access_all: boolean
          access_library: boolean
          access_own: boolean
          access_shared: boolean
          create: boolean
          delete: boolean
          download: boolean
          full_access: boolean
          manage: boolean
          rate: boolean
          react: boolean
          share: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
        password: {
          access_all: boolean
          access_library: boolean
          access_own: boolean
          access_shared: boolean
          create: boolean
          delete: boolean
          download: boolean
          full_access: boolean
          manage: boolean
          rate: boolean
          react: boolean
          share: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
        people: {
          access_all: boolean
          access_library: boolean
          access_own: boolean
          access_shared: boolean
          create: boolean
          delete: boolean
          download: boolean
          full_access: boolean
          manage: boolean
          rate: boolean
          react: boolean
          share: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
        photos: {
          access_all: boolean
          access_library: boolean
          access_own: boolean
          access_shared: boolean
          create: boolean
          delete: boolean
          download: boolean
          full_access: boolean
          manage: boolean
          rate: boolean
          react: boolean
          share: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
        places: {
          access_all: boolean
          access_library: boolean
          access_own: boolean
          access_shared: boolean
          create: boolean
          delete: boolean
          download: boolean
          full_access: boolean
          manage: boolean
          rate: boolean
          react: boolean
          share: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
        services: {
          access_all: boolean
          access_library: boolean
          access_own: boolean
          access_shared: boolean
          create: boolean
          delete: boolean
          download: boolean
          full_access: boolean
          manage: boolean
          rate: boolean
          react: boolean
          share: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
        sessions: {
          access_all: boolean
          access_library: boolean
          access_own: boolean
          access_shared: boolean
          create: boolean
          delete: boolean
          download: boolean
          full_access: boolean
          manage: boolean
          rate: boolean
          react: boolean
          share: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
        settings: {
          access_all: boolean
          access_library: boolean
          access_own: boolean
          access_shared: boolean
          create: boolean
          delete: boolean
          download: boolean
          full_access: boolean
          manage: boolean
          rate: boolean
          react: boolean
          share: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
        shares: {
          access_all: boolean
          access_library: boolean
          access_own: boolean
          access_shared: boolean
          create: boolean
          delete: boolean
          download: boolean
          full_access: boolean
          manage: boolean
          rate: boolean
          react: boolean
          share: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
        users: {
          access_all: boolean
          access_own: boolean
          create: boolean
          delete: boolean
          manage: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
        videos: {
          access_all: boolean
          access_library: boolean
          access_own: boolean
          access_shared: boolean
          create: boolean
          delete: boolean
          download: boolean
          full_access: boolean
          manage: boolean
          rate: boolean
          react: boolean
          share: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
        webdav: {
          access_all: boolean
          access_library: boolean
          access_own: boolean
          access_shared: boolean
          create: boolean
          delete: boolean
          download: boolean
          full_access: boolean
          manage: boolean
          rate: boolean
          react: boolean
          share: boolean
          subscribe: boolean
          update: boolean
          view: boolean
        }
      }
      ext: {
        plus: {}
      }
    }
    data: {
      tokens: any
      shares: any
    }
    expires_in: number
    id: string
    provider: string
    scope: string
    session_id: string
    status: string
    token_type: string
    user: {
      ID: number
      UID: string
      AuthProvider: string
      AuthMethod: string
      AuthID: string
      Name: string
      DisplayName: string
      Email: string
      Role: string
      Attr: string
      SuperAdmin: boolean
      CanLogin: boolean
      LoginAt: string
      WebDAV: boolean
      BasePath: string
      UploadPath: string
      CanInvite: boolean
      Details: {
        BirthYear: number
        BirthMonth: number
        BirthDay: number
        NameTitle: string
        GivenName: string
        MiddleName: string
        FamilyName: string
        NameSuffix: string
        NickName: string
        NameSrc: string
        Gender: string
        About: string
        Bio: string
        Location: string
        Country: string
        Phone: string
        SiteURL: string
        ProfileURL: string
        OrgTitle: string
        OrgName: string
        OrgEmail: string
        OrgPhone: string
        OrgURL: string
        CreatedAt: string
        UpdatedAt: string
      }
      Settings: {
        CreatedAt: string
        UpdatedAt: string
      }
      Thumb: string
      ThumbSrc: string
      CreatedAt: string
      UpdatedAt: string
    }
  }
  
export interface Album {
    UID?: string
    ParentUID?: string
    Thumb?: string
    Slug?: string
    Type?: string
    Title?: string
    Location?: string
    Category?: string
    Caption?: string
    Description?: string
    Notes?: string
    Filter?: string
    Order?: string
    Template?: string
    Path?: string
    State?: string
    Country?: string
    Year?: number
    Month?: number
    Day?: number
    Favorite?: boolean
    Private?: boolean
    PhotoCount?: number
    LinkCount?: number
    CreatedAt?: string
    UpdatedAt?: string
    DeletedAt?: string
}